---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-main

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - pod-monitor.yaml
    - ingress.yaml
    - middlewares.yaml

labels:
  - pairs:
      app.kubernetes.io/name: main-web
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: main
      com.sweetrpg/env: dev
    includeSelectors: false
    includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true
