---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-main

resources:
    - namespace.yaml
    - ../../base
    - configmaps.yaml
patchesStrategicMerge:
    - replicas.yaml

commonLabels:
    platform: sweetrpg
    app: main-web
    component: web
    package: main
    version: v1

generatorOptions:
    disableNameSuffixHash: true
