---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-main

resources:
    - ../../base
    - configmaps.yaml
    - podmonitor.yaml
    - ingress.yaml
    - destination-rules.yaml
    - secrets.yaml

labels:
  - pairs:
      platform: sweetrpg
      app: web
      component: web
      package: main
      version: v1

generatorOptions:
    disableNameSuffixHash: true
