---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: web-v1

spec:
    minAvailable: 1
    selector:
        matchLabels:
            platform: sweetrpg
            app: web
            component: web
            package: main
            version: v1
