---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: main-web-v1

spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: main-web
            platform: sweetrpg
            package: main
            component: web
            version: v1
